[workspace]
resolver = "2"
members = [
    "crates/webtau",
    "crates/webtau-macros",
]

[workspace.package]
version = "0.1.0-alpha.4"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/devallibus/gametau"
