[workspace]
resolver = "2"
members = [
    "crates/webtau",
    "crates/webtau-macros",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.77"
license = "Apache-2.0"
repository = "https://github.com/devallibus/gametau"
